version: '3.8'

services:
  your-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database_container5
    networks:
      - my-network

  database_container5:
    container_name: database_container5
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
    networks:
      - my-network

volumes:
  mongo_db:

networks:
  my-network:
    driver: bridge
